### PR TITLE
Update mod UI source artwork to prepare for fractional DPI/UI scaling

### PR DESCRIPTION
**Pull request by pchote**
This PR contains the updated source files for https://github.com/OpenRA/OpenRA/pull/17494, https://github.com/OpenRA/OpenRA/pull/17495, https://github.com/OpenRA/OpenRA/pull/17504, and https://github.com/OpenRA/OpenRA/pull/17506. We should hold off merging this until these PRs have been reviewed.

### CODE REVIEW

**Comment by pchote** [comment]
Updated with source artwork for D2k and TS.

**Review by dragunoff — CHANGES_REQUESTED** [review]
The `glyphs.svg` for RA, D2k and TS contains an unnecessary hidden layer holding a bunch of textures for TD's chrome (it was apparently copied over from TD's `chrome.svg`)

изображение

**Review by dragunoff — COMMENTED** [review]
@pchote Why was `ra/dialog.xcf` deleted? Doesn't that hold the artwork for the RA dialogs?

**Comment by pchote** [comment]
For the first version of the dialog.png yes - but all the later edits were made to the png directly, and not included in the xcf. The file just has the main dialog background and its border, with a layer for each baked component, so nothing of any real value.

**Comment by dragunoff** [comment]
> 
> 
> For the first version of the dialog.png yes - but all the later edits were made to the png directly, and not included in the xcf.

Alright. As I mentioned in https://github.com/OpenRA/OpenRA/pull/17495#pullrequestreview-337510424 the dialogs should be fairly easy to recreate in SVG.

**Comment by pchote** [comment]
I have cleaned up the layer structure in RA/D2k/TS the best I can with my wonky Inkscape version.

I have run out of time/enthusiasm to integrate the glyph for https://github.com/OpenRA/OpenRA/issues/17549 tonight, so this is still a pending fixup.

**Comment by pchote** [comment]
Updated TD and RA source with a glyph for https://github.com/OpenRA/OpenRA/issues/17549. I will hold off the other two until the first two have been accepted and merged.

**Comment by pchote** [comment]
The exported TD and RA artwork have now been merged.

Updated D2k and TS with the glyph for https://github.com/OpenRA/OpenRA/issues/17549.

**Comment by dragunoff** [comment]
I just figured that we could improve the glyph for the cash icon at 2x and 3x scale. This glyph was not in the source files when I worked on the TD UI and I had to recreate it pixel by pixel from the raster image. That's why it has some semi-transparent parts which look OK on 1x scale but become visible when scaled up. I have edited the glyph to use smooth curvers. Here is a visual to illustrate:
изображение

Sorry I didn't think of that before RA and TD PRs got merged. You can find the edited version here: https://github.com/dragunoff/ArtSrc/commit/4f0b9f6f9f6faea566395a8f6ae689cddb0ee24c if you want to use it.

**Comment by pchote** [comment]
Thanks, looks much better. I noticed some glitching when zooming in, so combined the shapes together and removed redundant nodes.

Updated D2k and TS glyphs and synced to the downstream PRs. I'll wait until those two PRs have been merged (in case there are any other improvements), then update TD and RA and file a new PR with the updated exports.

**Comment by pchote** [comment]
Updated for https://github.com/OpenRA/OpenRA/pull/17604.

**Comment by pchote** [comment]
Downstream PRs have now all been merged.

**Pull request merged**
