### PR TITLE
Add closed spawn sprites

### PR DESCRIPTION
**Pull request by ocdi**
This is the art changes corresponding to the closed spawns feature in https://github.com/OpenRA/OpenRA/pull/18425

It would be nice if Inkscape exported in a much similar format so the diffs aren't so massive here, all I did was copy one of the spawn circles and draw two lines to make the X.

### CODE REVIEW

**Comment by pchote** [comment]
I have fixed the ra/d2k/ts svgs locally to add the disabled glyph without requiring the massive diff, but cnc is being problematic. I will push a new branch that you can merge into this (and reexport, as it moves it by a couple of px) once done.

**Comment by pchote** [comment]
Ok, here's an updated version of the svgs: f90849278eb9dc8d11b40cdd14ab5191096c1576
and exported pngs and updated yaml: https://github.com/pchote/OpenRA/commit/20488a9f0289d305006eafbc63e5a490f798e19a

I moved some of the glyphs to better suit the sheet layout, and updated the node structure to fit the labelling/grouping structure.

**Comment by ocdi** [comment]
@pchote thanks for assisting cleaning up the artwork changes. I updated the other PR based on these changes.

**Comment by ocdi** [comment]
I effectively replaced my versions with your commit, I am guessing the same version of Inkscape and probably OS helped keep the diffs small.

**Pull request merged**
