### PR TITLE
Add sprite sources for the revamped TD ingame UI

### PR DESCRIPTION
**Pull request by dragunoff**
These are the source files used for OpenRA/OpenRA#16359

A little detail:
* Reorganize and document chrome.svg (with layers and object names)
* Add ingame chrome sprites (sidebar, command and stance bars)
* Add panels and buttons for GDI

### CODE REVIEW

**Comment by pchote** [comment]
A couple of thoughts here:
* Can you please add a translucent black rectangle for use by https://github.com/OpenRA/OpenRA/pull/16406? Yay graphical merge conflicts...

* Modern photoshop (intentionally?) breaks psd compatibility with all other image editors. Gimp, Pixelmator, and macOS's Preview app all load the new file as broken in different ways
Screenshot 2019-05-12 at 16 51 13
 It really sucks to be forced to buy into a subscription service to be able to edit our UI, but we unfortunately already suffer this for D2k and TS so I guess this one isn't shouldn't be a blocker.

**Comment by pchote** [comment]
The svg opens in Inkscape 0.92.3, but I don't seem to be able to select or edit any of the objects. Unlock All didn't help - what's going on here?

**Comment by dragunoff** [comment]
> The svg opens in Inkscape 0.92.3, but I don't seem to be able to select or edit any of the objects. Unlock All didn't help - what's going on here?
>
@pchote Probably all objects were locked. You can see that in the objects panel of Inkscape ("Objets > Objects" in the menu).

> Can you please add a translucent black rectangle for use by [OpenRA/OpenRA#16406](https://github.com/OpenRA/OpenRA/pull/16406)? Yay graphical merge conflicts...
> 
I have reorganized the sprite to open up some space for new panels. I need the exact transparency value. @teinarss - could you tell me the transparency level for that panel?

> Modern photoshop (intentionally?) breaks psd compatibility with all other image editors. Gimp, Pixelmator, and macOS's Preview app all load the new file as broken in different ways
>
> It really sucks to be forced to buy into a subscription service to be able to edit our UI, but we unfortunately already suffer this for D2k and TS so I guess this one isn't shouldn't be a blocker.
>
I have rebuilt everything in Inkscape. It actually came out better and there is way more control with vectors. Inkscape and SVG have come a long way :-)

**Comment by teinarss** [comment]
50%

**Comment by dragunoff** [comment]
Updated to add a 50% gray rectangle. 

Also made the black and transparent panels smaller (they don't have a texture so that's fine). That opens up even more space in the dialogs section for future elements.

**Comment by teinarss** [comment]
The rectangle / panel is black with 50% transparent.

**Comment by dragunoff** [comment]
> The rectangle / panel is black with 50% transparent.
>
Yes, that's what I meant - black with 50% transparency :-)

**Comment by pchote** [comment]
> I have rebuilt everything in Inkscape. It actually came out better and there is way more control with vectors. Inkscape and SVG have come a long way :-)

This is really impressive, and not at all what I was expecting!

LGTM, but lets hold off merging this until https://github.com/OpenRA/OpenRA/pull/16359 and https://github.com/OpenRA/OpenRA/pull/16406 are merged upstream in case further tweaks are needed.

**Comment by pchote** [comment]
Ready to merge once the change from https://github.com/OpenRA/OpenRA/pull/16625 is added.
Note that OpenRA/OpenRA#16406 ended up not needing its artwork change.

**Comment by dragunoff** [comment]
I'll update later today. Should I remove the gray square since it's not needed anymore?

**Comment by pchote** [comment]
Would be easier to leave it for now - this can be done in a future edit if needed to make space.

**Pull request merged**
