### PR TITLE
Added bot icon.

### PR DESCRIPTION
**Pull request by Dzierzan**
This PR adds new bot icon for https://github.com/OpenRA/OpenRA/pull/21489

### CODE REVIEW

**Review by PunkPun — COMMENTED** [review]
why is the robot icon placed in random places? Could it be spaced like the other icons in the file

**Comment by pchote** [comment]
Can we please put it with the other player type icons? (move the sell etc to make room)

**Comment by Dzierzan** [comment]
Done!

**Comment by pchote** [comment]
On second glance, IMO the boxyness of the icon feels out of place compared to the others. How about using https://icons.getbootstrap.com/icons/robot/ (MIT license, we're already using other bootstrap icons in our glyphs)?

**Comment by PunkPun** [comment]
I think this icon looks pretty good

**Comment by Dzierzan** [comment]
I aimed for simplicity without any roundness or unneeded details.

**Review by PunkPun — APPROVED** [review]

**Pull request merged**
